
<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>
<?php $pagelayout = $this->htmlEscape($_product->getPageLayout()); ?>
<?php if($pagelayout == '' || $pagelayout == 'one_column'){ ?>

<!--Start theme layout-->
<?php
$layout = Mage::helper("ExtraConfig")->themeOptions('productlayout');
$m = Mage::getModel('catalog/resource_eav_attribute')->loadByCode('catalog_product','productlayout');
if($m->getId() != null) {
	$lyt = $_product->getAttributeText('productlayout');
	if($lyt != null){ $layout = $lyt; }
}

if ($layout == null || $layout == 'default') { ?>


    <?php
    $mainImagePath = '';
    $galleryImages = $this->getGalleryImages();
    if (count($galleryImages) > 0) {
       
        
        $gallery .= '<ul class="slider6">';
        foreach ($galleryImages as $_image) {
            if ($_image->getFile() == $_product->getData('small_image')) {
                $mainImagePath = $this->getGalleryUrl($_image);
            }
            $gallery .= '<li>'
                     .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                     .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                     .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(84,77) . '" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                     .  '</a></li>';
        }
        $gallery .= '</ul>';
    } ?>

<?php } elseif ($layout == 'horizontal') { ?>


    <?php
    $mainImagePath = '';
    $galleryImages = $this->getGalleryImages();
    if (count($galleryImages) > 0) {
        
        $gallery .= '<ul class="slider6">';
        foreach ($galleryImages as $_image) {
            if ($_image->getFile() == $_product->getData('small_image')) {
                $mainImagePath = $this->getGalleryUrl($_image);
            }
            $gallery .= '<li>'
                     .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                     .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                     .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(84,77) . '" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                     .  '</a></li>';
        }
        $gallery .= '</ul>';
    } ?>

<?php } elseif ($layout == 'vertical') { ?>


    <?php
    $mainImagePath = '';
    $galleryImages = $this->getGalleryImages();
    if (count($galleryImages) > 0) {
        
        $gallery .= '<ul class="slider6">';
        foreach ($galleryImages as $_image) {
            if ($_image->getFile() == $_product->getData('small_image')) {
                $mainImagePath = $this->getGalleryUrl($_image);
            }
            $gallery .= '<li>'
                     .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                     .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                     .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(84,77) . '" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                     .  '</a></li>';
        }
        $gallery .= '</ul>';
    } ?>


<?php } ?>

<?php if ($layout == null || $layout == 'default') { ?>


    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <p class="product-image product-image-zoom">
            <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
            <?php
                $_img = '<img id="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
            </a>
        </p>
    <?php else: ?>
        <p class="product-image">
            <?php
                $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(374,498).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
    <?php endif; ?>
    
    <?php if(isset($gallery)): ?>
        <div class="default-views more-views">
            <?php echo $gallery; ?>
        </div>
    <?php endif; ?>

 
<?php } elseif ($layout == 'horizontal') { ?>


    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <p class="product-image product-image-zoom">
            <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
            <?php
                $_img = '<img id="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
            </a>
        </p>
    <?php else: ?>
        <p class="product-image">
            <?php
                $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(500,498).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
    <?php endif; ?>
    
    <?php if(isset($gallery)): ?>
        <div class="horizontal-views more-views">
            <?php echo $gallery; ?>
        </div>
    <?php endif; ?>
    
    
<?php } elseif ($layout == 'vertical') { ?>


    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <p class="product-image product-image-zoom">
            <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
            <?php
                $_img = '<img id="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
            </a>
        </p>
    <?php else: ?>
        <p class="product-image">
            <?php
                $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(300,498).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
    <?php endif; ?>
    
    <?php if(isset($gallery)): ?>
        <div class="vertical-views more-views">
            <?php echo $gallery; ?>
        </div>
    <?php endif; ?>
    
    
<?php } ?>
    


<!--End theme layout-->

<?php } else { ?>

    <?php
    $mainImagePath = '';
    $galleryImages = $this->getGalleryImages();
    if (count($galleryImages) > 0) {
       
        
        $gallery .= '<ul class="slider6">';
        foreach ($galleryImages as $_image) {
            if ($_image->getFile() == $_product->getData('small_image')) {
                $mainImagePath = $this->getGalleryUrl($_image);
            }
            $gallery .= '<li>'
                     .  '<a href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                     .  'rel="popupWin:\'' . $this->getGalleryUrl($_image) . '\', useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) .  '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                     .  '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(84,77) . '" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                     .  '</a></li>';
        }
        $gallery .= '</ul>';
    } ?>
 
    <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
        <p class="product-image product-image-zoom">
            <a rel="<?php echo $this->renderCloudOptions(); ?>" gallery="<?php echo $mainImagePath; ?>" href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
            <?php
                $_img = '<img id="image" src="'.$this->getCloudImage($_product).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
            </a>
        </p>
    <?php else: ?>
        <p class="product-image">
            <?php
                $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'image')->resize(374,498).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </p>
    <?php endif; ?>
    
    <?php if(isset($gallery)): ?>   
        <div class="default-views more-views">
           <?php echo $gallery; ?>       
        </div>
    <?php endif; ?>
 
<?php } ?>