    
		
<?php
$ajaxcart = Mage::helper("ExtraConfig")->themeOptions('ajaxcart');
$page = Mage::app()->getLayout()->getBlock('root')->getTemplate();
 $newsaleicon = Mage::helper("ExtraConfig")->themeOptions('newsaleicon');
?>
<div class="latest-product">
<div class="new-arrow">
    <h2 class="page-title subtitle"><?php echo $this->__('Latest Products') ?></h2>
</div>
			
    <?php if (($_products = $this->getProductCollection()) && $_products->getSize()): ?>
    <div class="slider1">
	<?php if($page == 'page/1column.phtml') { ?>      
	    <?php $columnCount = 5; $this->setColumnCount($columnCount); $_columnCount = $this->getColumnCount(); ?>
	<?php } elseif($page == 'page/2columns-right.phtml' || $page == 'page/2columns-left.phtml') { ?>
	    <?php $columnCount = 4; $this->setColumnCount($columnCount); $_columnCount = $this->getColumnCount(); ?>
	<?php } else { ?>
	    <?php $columnCount = 3; $this->setColumnCount($columnCount); $_columnCount = $this->getColumnCount(); ?>
	<?php } ?>
	<?php $i=0; foreach ($_products->getItems() as $_product): ?>
	
	<?php if ($i++%$_columnCount==0): ?>
	    <?php if($page == 'page/1column.phtml') { ?>
	    <ul class="products-grid products-grid-full">
	    <?php } elseif($page == 'page/2columns-right.phtml' || $page == 'page/2columns-left.phtml') { ?>
	    <ul class="products-grid products-grid-side">
	    <?php } else { ?>
	    <ul class="products-grid products-grid-middle">
	    <?php } ?>
	<?php endif ?>
	      
	      <li class="latest-product item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
		    
		    <div class="content_top">
			
			<?php if($newsaleicon == '1') { ?> 
			<?php $adate = date('Y-m-d');  //echo 'frpm:-'.$_product->special_from_date.'----';echo "to:-".$_product->special_to_date.'--';
				$a= 0;
				if($_product->special_from_date != null && $_product->special_to_date == "")
				{
				    if( $adate >= $_product->special_from_date)
				    {
					    $a = 1; 
				    }
				}
				if($_product->special_from_date != "" && $_product->special_to_date != "")
				{
				    if($adate >= $_product->special_from_date && $adate <= $_product->special_to_date)
				    {
				    $a = 1; 
				    }
				}
				    
				    if($a == 1){ ?>
				   <div class="sale"><label><?php echo $this->__('SALE') ?></label></div>
				    <?php } ?>
				
			<?php } ?>
			
			<?php if($ajaxcart == '2') { ?>
			    <a href='<?php echo $this->getUrl('ajax/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox quick-view' id='fancybox<?php echo $_product->getId()?>'><div class="tooltip"><?php echo $this->__('Quick View') ?><div class="errow"></div></div></a>
			<?php } ?>
			<a  href="<?php echo $_product->getProductUrl() ?>" class="product-image" title="<?php echo $this->htmlEscape($_product->getName()) ?>" >
			    <img class="small-image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(430) ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
			    <img class="thumbnail" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(430) ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
			</a>
			<div class="productname">
			    <?php if($page == 'page/3columns.phtml') { ?>      
			      <?php  $productName = $this->htmlEscape($_product->getName());
			      if(strlen($productName) > 18) {
				      $productName = mb_strimwidth($productName,0,18,"...",'utf-8');
			      } ?>
			    <?php } else { ?>
				<?php  $productName = $this->htmlEscape($_product->getName());
				if(strlen($productName) > 23) {
					$productName = mb_strimwidth($productName,0,23,"...",'utf-8');
				} ?>
			    <?php } ?>
			  <h3 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $productName; ?></a></h3>					    
			</div>
		    </div>
		    
		    <div class="productgrid-area">
			<div class="vert">
			  <?php echo $this->getPriceHtml($_product, true, '-new') ?>
			</div>
			<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
			<div class="actions">
			      <?php if($_product->isSaleable()): ?>
				  <?php if($ajaxcart == '1' || $ajaxcart == '2') { ?>
				      <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) { ?>
					<div class="ajax-button">
					    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart ajx-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button> 
					    <div id='ajax_loader<?php echo $_product->getId()?>' class="ajaxcartpro_progress" style="display: none;">
						<img src="<?php echo $this->getSkinUrl('ajaxcart/images/al.gif'); ?>">
					    </div>
					</div>
				      <?php } else { ?>
					<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
				      <?php }  ?>
				  <?php } else { ?>
				      <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
				  <?php } ?>
			      <?php else: ?>
				  <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
			      <?php endif; ?>
			      <div class="add-to-links">
				  <?php if ($this->helper('wishlist')->isAllow()) : ?>
				      <a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" title="<?php echo $this->__('Add to Wishlist') ?>" class="link-wishlist"><div class="tooltip"><?php echo $this->__('Add to Wishlist') ?><div class="errow"></div></div></a>
				  <?php endif; ?>
				  <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
				      <span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" title="<?php echo $this->__('Add to Compare') ?>" class="link-compare"><div class="tooltip"><?php echo $this->__('Add to Compare') ?><div class="errow"></div></div></a>
				  <?php endif; ?>
			      
			      </div> 
			</div>
		    </div>
		    
	      </li>
	      
	<?php if ($i%$_columnCount==0 || $i==count($_products)): ?>	
	</ul>
	<?php endif ?>
	
	<?php endforeach; ?>
	      
    </div>
    <?php endif; ?>
	    
</div>	
	    